### ISSUE TITLE
After cropping and uploading selected I was depressed and then Upload another photo took me to Home page

### ISSUE THREAD

**Issue by Coppell** [dxywill/Mania#19]

**Comment by dxywill** [comment]
I changed the policy a little bit, I add code to invalidate the session after submit the survey. So if the user want to upload another image, he/she needs to log in again. The reason of doing this is because if we allow them to upload several images at one time, they may have the illusion that we are tracking the user, because we 'remember the user' and automatically associate the following submission with the first log in. However, may be we could talk about this in the meeting.

**Comment by Coppell** [comment]
Sure. Can Discuss.

**Comment by dxywill** [comment]
reverted  it back, so closing this issue
